
development:
  adapter: postgresql
  database: rantface_database_development
  host: localhost
  pool: 5
  username: collingraves
  password: password
  timeout: 5000

test:
  adapter: postgresql
  database: rantface_database_test
  host: localhost
  pool: 5
  username: collingraves
  password: password
  timeout: 5000

production:
  adapter: postgresql
  database: rantface_database_production
  host: localhost
  pool: 5
  username: collingraves
  password: password
  timeout: 5000

